version: '3.8'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: ./docker/dockerfiles
            dockerfile: nginx.dockerfile
        volumes:
            - ./:/var/www:delegated

        ports:
            - '8000:80'
        depends_on:
            - php
            - node
            - mysql
        networks:
            - laravel

    php:
        build:
            context: ./docker/dockerfiles
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./:/var/www:delegated
        networks:
            - laravel
        environment:
            - 'DB_PORT=3306'
            - 'DB_HOST=mysql'
        links:
            - mysql

    mysql:
        image: mysql:8.0
        ports:
            - '${DB_PORT}:${DB_PORT}'
        env_file:
            - ./.env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    node:
        image: node:18-alpine
        ports:
            - '3000:3000'
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
        networks:
            - laravel

volumes:
    db_data:
