version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: "nginx:stable-alpine"
    ports: 
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel 
    depends_on:
      - mysql
      - php
    networks:
      - laravel
  php:  
    build:
      context: ./docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
  # phpmyadmin:
  #   image: phpmyadmin:5.2.0
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: ${DB_HOST}
  #     PMA_USER: ${DB_USERNAME}
  #     PMA_PASSWORD: ${DB_PASSWORD}
  #     PMA_PORT: ${DB_PORT}
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 8888:80

  composer:
    build:
      context: ./docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/laravel
    networks:
      - laravel

  artisan:
    build:
      context: ./docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: npm
    restart: always
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 5173:5173
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel


volumes:
  db_data: